services:
  mysql:
    image: mysql:8.0
    container_name: pilketang_mysql
    restart: unless-stopped
    environment:
      # Memetakan dari file .env Anda
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "127.0.0.1:3306:3306" # Membatasi akses hanya dari localhost VPS agar aman
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - pilketang_network

  backend:
    build: .
    container_name: pilketang_backend
    restart: unless-stopped
    env_file:
      - .env # Menginstruksikan backend untuk membaca file .env yang sama
    networks:
      - pilketang_network
    depends_on:
      - mysql

networks:
  pilketang_network:
    driver: bridge

volumes:
  mysql_data:
