services:
  mysql:
    image: mysql:8.0
    container_name: pilketang_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: SabtuC3riaRt
      MYSQL_DATABASE: pilketang25
      MYSQL_USER: pilketang
      MYSQL_PASSWORD: S@btuK3ce312
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
